---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check if swapfile exists
      stat:
        path=/swapfile
        get_checksum=False
        get_md5=False
      register: swapfile

    - name: Enable swapfile with length 2G
      command: "{{ item }}"
      with_items:
        - fallocate -l 2G /swapfile
        - mkswap /swapfile
        - swapon /swapfile
      when: swapfile.stat.exists == False

    - name: Make sure swapfile is included in /etc/fstab
      mount:
        name=swap
        src=/swapfile
        fstype=swap
        state=present

    - name: Copy etc files
      copy:
        src=files/etc/{{ item.name }}
        dest=/etc/{{ item.name }}
        owner=root
        group=root
        mode={{ item.mode }}
      with_items:
        - name: apt/sources.list
          mode: u=rw,g=r,o=r

    - name: Add public key allow access, github.com/sunsongxp.keys
      authorized_key:
        user=root
        key=https://github.com/sunsongxp.keys

    - name: Allow ssh to root
      lineinfile:
        dest=/etc/ssh/sshd_config
        line='UseDNS no'
        line='PermitRootLogin yes'
        regexp='^PermitRootLogin'
        state=present
      notify: restart ssh

    - name: Upgrade the system
      apt:
        update_cache=yes
        upgrade=yes

    - name: Install extra packages
      apt:
        update_cache=no
        name={{ item }}
      with_items:
        - ipython
        - python-dev
        - python-pip
        - build-essential
        - ncdu
        - silversearcher-ag
        - git
        - htop
        - iotop
        - sysstat
        - iptraf
        - iftop
        - nmon

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: common
