---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Copy etc files
      copy:
        src=files/etc/{{ item.name }}
        dest=/etc/{{ item.name }}
        owner=root
        group=root
        mode={{ item.mode }}
      with_items:
        - name: apt/sources.list
          mode: u=rw,g=r,o=r

    - name: Upgrade the system
      apt:
        update_cache=yes
        upgrade=yes
